// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqhskofgmsayhbuhknqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaHNrb2ZnbXNheWhidWhrbnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjg4NjcsImV4cCI6MjA3MTYwNDg2N30.LrFIGbaENEvxZWyT3KA2s87sX6iXGCoIbLqHiWaqE5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});